// Mocks generated by Mockito 5.4.4 from annotations
// in ca_flutter_test/test/features/onboarding/data/repositories/onboarding_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:ca_flutter_test/src/features/onboarding/data/datasources/onboarding_datasource.dart'
    as _i2;
import 'package:ca_flutter_test/src/features/onboarding/interactor/entities/onboarding_page_contents_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OnboardingDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingDatasource extends _i1.Mock
    implements _i2.OnboardingDatasource {
  @override
  List<_i3.OnboardingPageContentsDTO> getDefaultContents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultContents,
          [],
        ),
        returnValue: <_i3.OnboardingPageContentsDTO>[],
        returnValueForMissingStub: <_i3.OnboardingPageContentsDTO>[],
      ) as List<_i3.OnboardingPageContentsDTO>);
}
