// Mocks generated by Mockito 5.4.4 from annotations
// in ca_flutter_test/test/features/product_store/data/repositories/product_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ca_flutter_test/src/features/product_store/interactor/datasources/i_discount_remote_ds.dart'
    as _i6;
import 'package:ca_flutter_test/src/features/product_store/interactor/datasources/i_favorite_products_ds.dart'
    as _i5;
import 'package:ca_flutter_test/src/features/product_store/interactor/datasources/i_products_remote_ds.dart'
    as _i2;
import 'package:ca_flutter_test/src/features/product_store/interactor/entities/product_entity.dart'
    as _i4;
import 'package:ca_flutter_test/src/shared/modules/internet/interactor/services/i_network_status_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductsRemoteDataSource extends _i1.Mock
    implements _i2.IProductsRemoteDataSource {
  @override
  _i3.Future<List<_i4.ProductEntity>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
      ) as _i3.Future<List<_i4.ProductEntity>>);
}

/// A class which mocks [IFavoriteProductsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFavoriteProductsDataSource extends _i1.Mock
    implements _i5.IFavoriteProductsDataSource {
  @override
  _i3.Future<List<_i4.ProductEntity>> getFavoriteProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteProducts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
      ) as _i3.Future<List<_i4.ProductEntity>>);
}

/// A class which mocks [IDiscountRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDiscountRemoteDataSource extends _i1.Mock
    implements _i6.IDiscountRemoteDataSource {
  @override
  _i3.Future<double> getDiscount({String? productId}) => (super.noSuchMethod(
        Invocation.method(
          #getDiscount,
          [],
          {#productId: productId},
        ),
        returnValue: _i3.Future<double>.value(0.0),
        returnValueForMissingStub: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}

/// A class which mocks [INetworkStatusService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkStatusService extends _i1.Mock
    implements _i7.INetworkStatusService {
  @override
  _i3.Future<bool> getInternetStatus() => (super.noSuchMethod(
        Invocation.method(
          #getInternetStatus,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
