#! --- PROJECT CONFIGS ---
name: ca_flutter_test
description: "Conta Azul - Flutter Test"
version: 1.0.0+1


#! --- SDK VERSION ---
environment:
  sdk: '>=3.4.3 <4.0.0'


  #! --- PRODUCTION DEPENDENCIES ---
dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT:
  # Reference: https://asp.flutterando.com.br/docs/introduction/getting-started
  asp: ^2.0.0

  # ROUTING AND INJECTION:
  # Reference: https://www.youtube.com/watch?v=EdHbE817gyo
  flutter_modular: ^6.3.4

  # CHANGE DEFAULT NATIVE SPLASH SCREEN:
  # Reference: https://www.youtube.com/watch?v=x0a6_ILbvAk
  flutter_native_splash: ^2.4.1

  # CHANGE DEFAULT APP ICON:
  # Reference: https://www.youtube.com/watch?v=_GdG4u7hfAM
  flutter_launcher_icons: ^0.13.1

  # HTTP CLIENT:
  # Reference: https://pub.dev/packages/http
  http: ^1.2.2
  
  # SVG RENDERING:
  # Reference: https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1

  # BACKEND SERVICES:
  # # Reference: https://pub.dev/packages/firebase_core
  # firebase_core: ^2.24.2
  # # Reference: https://pub.dev/packages/firebase_auth
  # firebase_auth: ^4.16.0

  # TEXT RESIZING:
  # Reference: https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0

  # CUSTOM HAPTIC FEEDBACK:
  # Reference: https://pub.dev/packages/vibration
  vibration: ^1.9.0

  # CUSTOM ANIMATIONS:
  # Reference: https://pub.dev/packages/flutter_animate
  flutter_animate: ^4.5.0

  # CLASS EQUALITY:
  # Reference: https://pub.dev/packages/equatable
  equatable: ^2.0.5

  # LOCAL STORAGE:
  # Reference: https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.3

  # SECURE STORAGE:
  # Reference: https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2  

  # EMAIL VALIDATOR:
  # Reference: https://pub.dev/packages/email_validator
  email_validator: ^3.0.0


  # INTERNET CONNECTION CHECKER:
  # Reference: https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^2.0.0


#! --- DEVELOPMENT DEPENDENCIES ---
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

  # AUTOMATIC ASSET CLASS GENERATION:
  # Reference: https://pub.dev/packages/flutter_gen
  flutter_gen_runner: ^5.6.0
  # Reference: https://pub.dev/packages/build_runner
  build_runner: ^2.4.11

  # MOCKS AND TESTS:
  mockito: ^5.4.4


#! --- DEPENDENCIES CONFIGURATIONS ---
# FLUTTER GEN RUNNER (ASSETS CLASS GENERATION):
flutter_gen:
  output: lib/src/shared/design_system/config/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# FLUTTER NATIVE SPLASH:
flutter_native_splash:
  color: "#00B2F6"
  android_12:
    # Splash screen background color.
    color: "#00B2F6"
    image: "assets/images/app_icon_android_12.png"
    icon_background_color: "#00B2F6"

# FLUTTER LAUNCHER ICONS:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  #! --- ASSET IMPORTS ---
  assets:
  # IMAGES
    - assets/images/
  # FONTS
    - assets/fonts/
  # SVG
    - assets/svg/


  #! --- FONT CONFIGS ---
  fonts:
  #? Housechka Pro - Font Family
    - family: HouschkaPro
      fonts:
      # EXTRA BOLD
        - asset: assets/fonts/HouschkaPro-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/HouschkaPro-ExtraBoldItalic.ttf
          style: italic
          weight: 800
      # BOLD
        - asset: assets/fonts/HouschkaPro-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/HouschkaPro-BoldItalic.ttf
          style: italic
          weight: 700
      # SEMI BOLD
        - asset: assets/fonts/HouschkaPro-DemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/HouschkaPro-DemiBoldItalic.ttf
          style: italic
          weight: 600
      # MEDIUM
        - asset: assets/fonts/HouschkaPro-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/HouschkaPro-MediumItalic.ttf
          style: italic
          weight: 500
      # LIGHT
        - asset: assets/fonts/HouschkaPro-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/HouschkaPro-LightItalic.ttf
          style: italic
          weight: 300
      # THIN
        - asset: assets/fonts/HouschkaPro-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/HouschkaPro-ThinItalic.ttf
          style: italic
          weight: 100


#! ------------------------------------------------------------------------------------------------------
#! -------------------------------------- COMMANDS CHEAT SHEET ------------------------------------------
#! ------------------------------------------------------------------------------------------------------

#! ----------------------------------------------------------
#! ---------------------- ASSETS GEN ------------------------
#! ----------------------------------------------------------
#? Command used to generate the asset class with flutter_gen:
#  dart run build_runner build
#! ----------------------------------------------------------
#! ----------------------- APP NAME -------------------------
#! ----------------------------------------------------------
#? Command used to change the application name on the device:
#  flutter pub global run rename --appname "APP_NAME_HERE"
#! ----------------------------------------------------------
#! ----------------------- APP ICON -------------------------
#! ----------------------------------------------------------
#? Command used to change the application icon:
#  dart run flutter_launcher_icons
#! ----------------------------------------------------------
#! --------------------- NATIVE SPLASH ----------------------
#! ----------------------------------------------------------
#? Command used to update changes made to application native splash screen:
#  dart run flutter_native_splash:create
#! ----------------------------------------------------------
#! --------------------- APP BUNDLE ID ----------------------
#! ----------------------------------------------------------
#? Command used to modify the BUNDLE ID of the application, where my_website.com and application_name are the new values:
#  flutter pub global run rename --bundleId com.website_name.app_name
#! ----------------------------------------------------------
#! --------------------- APP PROFILING ----------------------
#! ----------------------------------------------------------
#? VSCODE Command (CTRL SHIFT P or COMAND SHIFT P) used to open dart devtools for application profiling:
#  devtools
#! ----------------------------------------------------------
#! ------------ APP BUNDLE GENERATION - ANDROID -----------
#! ----------------------------------------------------------
#? MUST CHANGE ANDROID > KEY.PROPERTIES if the "upload-keystore.jks" changes location!
#? Builds application .aab file for android app bundle releases:
#  flutter build appbundle
