// Mocks generated by Mockito 5.4.4 from annotations
// in ca_flutter_test/test/features/authentication/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ca_flutter_test/src/features/authentication/data/datasources/create_account_ds.dart'
    as _i2;
import 'package:ca_flutter_test/src/features/authentication/data/datasources/delete_account_ds.dart'
    as _i4;
import 'package:ca_flutter_test/src/features/authentication/data/datasources/login_ds.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CreateAccountDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccountDataSource extends _i1.Mock
    implements _i2.CreateAccountDataSource {
  @override
  _i3.Future<int> createAccount({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [DeleteAccountDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccountDataSource extends _i1.Mock
    implements _i4.DeleteAccountDataSource {
  @override
  _i3.Future<bool> deleteCurrentAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentAccount,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [LoginDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginDataSource extends _i1.Mock implements _i5.LoginDataSource {
  @override
  _i3.Future<String> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<String>);
}
