// Mocks generated by Mockito 5.4.4 from annotations
// in ca_flutter_test/test/features/product_store/interactor/usecases/get_favorite_products_uc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ca_flutter_test/src/features/product_store/interactor/dtos/products_dto.dart'
    as _i5;
import 'package:ca_flutter_test/src/features/product_store/interactor/entities/product_entity.dart'
    as _i4;
import 'package:ca_flutter_test/src/features/product_store/interactor/repositories/i_product_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductsRepository extends _i1.Mock
    implements _i2.IProductsRepository {
  @override
  _i3.Future<List<_i4.ProductEntity>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
      ) as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<List<_i4.ProductEntity>> getFavoriteProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteProducts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
      ) as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<void> saveFavoriteProducts({required _i5.ProductsDTO? products}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavoriteProducts,
          [],
          {#products: products},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
